Repository panteLx/easynews-plus-plus, pull requests merged in 2025-04, with the labels that each got.

#26 feat: Bulgarian translation
  packages/addon/src/i18n/index.ts
Labels: enhancement

#44 docs: update README to include Android Mobile support
  README.md
Labels: documentation

#45 feat: add new custom title and translation for "To the Left of the F…
  custom-titles.json
Labels: enhancement

#52 feat: add new configuration options for stream quality and file size
  README.md
  packages/addon/src/addon.ts
  packages/addon/src/custom-template.ts
  packages/addon/src/i18n/index.ts
  packages/addon/src/manifest.ts
Labels: documentation, enhancement
